.data

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	Í¼Æ¬×ÊÔ´
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
bgTest			dword	0
_bg1			dword	0
_bg2			dword	0	
_bg3			dword	0	
_bg4			dword	0
_bg5			dword	0	
_bgwait			dword	0
_bgready		dword	0
_stop			dword	0
_square			dword	0
_bgWaitConnect	dword	0
_bgConnectErr	dword	0
_laugh			dword	0
_boomPic		dword	0